name: "Build Action"
on:
  push:
  pull_request:
  workflow_dispatch:

permissions: write-all

jobs:
  Build-LiteLoader:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Main Repository
        uses: actions/checkout@v4
      - name: Use Node.js 20.X
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Build NapCat.Framework
        run: |
          npm i && cd napcat.webui && npm i && cd .. || exit 1
          npm run build:framework && npm run depend || exit 1
          rm package-lock.json
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: NapCat.Framework
          path: dist
  Build-Shell:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Main Repository
        uses: actions/checkout@v4
      - name: Use Node.js 20.X
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Build NapCat.Shell
        run: |
          npm i && cd napcat.webui && npm i && cd .. || exit 1
          curl -sSL https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2025-04-16-12-54/ffmpeg-n7.1.1-6-g48c0f071d4-win64-lgpl-7.1.zip -o ffmpeg.zip
          unzip -q ffmpeg.zip -d ffmpeg && rm ffmpeg.zip
          cd ffmpeg
          mv ffmpeg.exe ../external/ffmpeg/ffmpeg.exe
          mv ffprobe.exe ../external/ffmpeg/ffprobe.exe
          cd ..
          npm run build:shell && npm run depend || exit 1
          rm package-lock.json
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: NapCat.Shell
          path: dist
